# Generated by Django 6.0.4 on 2026-05-22 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_app', '0010_problem_input_variable'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
    ]
