# Generated by Django 6.0.4 on 2026-05-26 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_app', '0011_problem_is_hidden'),
    ]

    operations = [
        migrations.AddField(
            model_name='hackathonstate',
            name='hints_enabled',
            field=models.BooleanField(default=False, help_text='Allow teams to request AI hints on problems'),
        ),
    ]
