# Generated by Django 6.0.4 on 2026-05-26 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_app', '0012_hackathonstate_hints_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='hackathonstate',
            name='tutorial_is_finished',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hackathonstate',
            name='tutorial_is_started',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hackathonstate',
            name='tutorial_start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='problem',
            name='is_tutorial',
            field=models.BooleanField(default=False),
        ),
    ]
